name: CI
"on":
  push: null
  schedule:
  - cron: 01 13 * * SAT
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to dockerhub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: ${{ secrets.DOCKER_USERNAME }}/wrapdispute:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/wrapdispute:latest
        cache-to: type=inline
  test31:
    needs: buildx
    runs-on: ubuntu-latest
    container:
      image: docker.io/${{ secrets.DOCKER_USERNAME }}/wrapdispute:latest
    steps:
    - name: test
      run: bash -x /test31.sh
